### ISSUE TITLE
Merge ferns textures into one

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#10]
Currently you only have one leaf per texture, with smart placement, I think you can combine them in a single 256x256 texture. That would make it easier for maintenance.

**Comment by BigTiger7** [comment]
I would do that, but each texture is sharing the same mesh, which they will share the same uv mapping. To have the textures in one png file I would need six more meshes?

**Comment by StanleySweet** [comment]
Ah yeah nevermind then :)
