### ISSUE TITLE
Remove caps from names

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#2]
Meshes, Textures and actors should have no caps in their names "Ferns_AO"

**Comment by StanleySweet** [comment]
Still missing  :) https://github.com/BigTiger7/0ad_flora/tree/master/Bigtiger_Flora_Mod_dev/art/textures/ui/session/icons/mappreview

**Comment by BigTiger7** [comment]
Was bugged, showed lower case for desktop, but not in github. Has now been fixed

**Comment by StanleySweet** [comment]
Still missing pine_Tree_Tall_XXX.dae
