### ISSUE TITLE
Add eyecandy flora from the eyecandy mod :)

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#3]
https://github.com/0ADMods/eyecandy/tree/master/art/actors/flora/trees

**Comment by BigTiger7** [comment]
added a fern that you wanted changed. :)

**Comment by StanleySweet** [comment]
Thanks, can you add as is or improve the trees as well ? :)

**Comment by BigTiger7** [comment]
I'll try to add/improve the trees as well. Will start working on them mid week.

**Comment by StanleySweet** [comment]
![Plotting Racoon](http://www.quickmeme.com/img/3b/3b84cd3513d3cb4cf5acd4de5109d4afe2bdd5232cf7bd9ea8dc888fd76fc2a5.jpg)

It's a pleasure doing business with you. :)

**Comment by StanleySweet** [comment]
Any news ? :)

**Comment by BigTiger7** [comment]
I'm still working on the dead trees. I'll try to have them ready for Monday. Trying to make the dead trees look natural.

**Comment by StanleySweet** [comment]
Will you keep mine ? :)

**Comment by BigTiger7** [comment]
I like the fallen dead trees logs you made, but they are a bit big. Trying to get something closer to this for fallen dead trees for forest floor.
![dead forest floor](https://user-images.githubusercontent.com/50048842/57225372-3092ee00-6fda-11e9-98ee-93bd3f14f70b.png)

**Comment by StanleySweet** [comment]
Well some trunks can be big :) they did not use to cut trees as often as we do :)

**Comment by BigTiger7** [comment]
True, can I then use two of your trees if that's okay with you. The trunk with the mushrooms on it is my favorite. :)

**Comment by StanleySweet** [comment]
Great :) Feel free to reuse the mushrooms as well :)
