### ISSUE TITLE
Move all the files to the root directory

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#5]
> The way people are putting their mods on Github makes it difficult to clone them. I have to go one step higher to clone it to desktop, but then the mod doesn't show in the list. :) @Bigtiger, the mod's contents should be in the top level, along with mod.json, etc.﻿ The license and readme can go with the mod contents no problem

**Comment by BigTiger7** [comment]
Thanks, I made the changes. It should now be easier.

**Comment by StanleySweet** [comment]
Great job
