### ISSUE TITLE
Remove useless empty lines in XML files.

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#8]
Some of the files (temperate_dead_forest.xml, art/terrains/new_temp/terrains.xml...) etc have useless new lines in their files, they should be removed.

**Comment by StanleySweet** [comment]
For actor files, you can use the provided actor editor in the game, or if it crashes too much and you are on windows you can use https://wildfiregames.com/forum/index.php?/topic/24055-beta-c-actor-editor-for-windows-users/

**Comment by BigTiger7** [comment]
Believe all empty line should be removed, except for the last line which you brought to my attention is need for unix/linux.

**Comment by StanleySweet** [comment]
This is starting to look really good ! Only thing I've seen is sometimes indentation is messed up for the textures. Anything else you'd like to add before I add this to the main game ? :)

**Comment by BigTiger7** [comment]
If there is a texture you think needs some rework let me know which one should be touched up.

**Comment by StanleySweet** [comment]
I'll have a look and see if there is feedback I can give you. 

Can you look at the list here https://wildfiregames.com/forum/index.php?/topic/17730-art-dev-task-tracking/#comments
and tell me which trees you have done ?

**Comment by StanleySweet** [comment]
Oh by messed indentation I meant in the XML files like

```xml
<textures>
    <texture file="5656"/>
    </textures>
```
instead of

```xml
<textures>
    <texture file="5656"/>
</textures>
```

**Comment by BigTiger7** [comment]
So making the the code structure as follow would be the correct way.

    <variant frequency="1" name="tree_pine_tall_1">
      <mesh>gaia/pine_tree_tall_1.dae</mesh>
      <props>
        <prop actor="props/special/eyecandy/ground_tree_decal_01.xml" attachpoint="root"/>
        </props>	  
      <textures>
	    <texture file="gaia/tree_pine_tall_1.png" name="baseTex"/>		
	    </textures>	  
    </variant>

**Comment by StanleySweet** [comment]
```xml
<variant frequency="1" name="tree_pine_tall_1">. 
  <mesh>gaia/pine_tree_tall_1.dae</mesh>
  <props>
    <prop actor="props/special/eyecandy/ground_tree_decal_01.xml" attachpoint="root"/>
  </props>	  
  <textures>
    <texture file="gaia/tree_pine_tall_1.png" name="baseTex"/>
  </textures>	  
</variant>
```

**Comment by StanleySweet** [comment]
You can use autoformatters or the actor editor for that purpose :)
