### ISSUE TITLE
Add final newlines 

### ISSUE THREAD

**Issue by StanleySweet** [BigTiger7/0ad_flora#9]
As we have a lot of unix users, (not as much as windows user) there should be final new line in the files

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

Ex: temp_grass_01_mod.xml doesn't have a final new line.

**Comment by BigTiger7** [comment]
Thanks Stan, I'll go through and put this final line in all the xml files that might be missing it.
